--
-- PostgreSQL database dump
--

\restrict fO0ykDwu2zhfypywCLgYo2y0NxQ8jTk2ozfHQE79X0e9oaFhRJQ0RZtuYQM5J5U

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg13+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.project_access DROP CONSTRAINT IF EXISTS fkmss0egoop5a53m3rsqerl68d0;
ALTER TABLE IF EXISTS ONLY public.user_roles DROP CONSTRAINT IF EXISTS fkh8ciramu9cc9q3qcqiv4ue8a6;
ALTER TABLE IF EXISTS ONLY public.projects DROP CONSTRAINT IF EXISTS fkgdyu73mg454kk9iys9567qft7;
ALTER TABLE IF EXISTS ONLY public.projects DROP CONSTRAINT IF EXISTS fkfk8sohdfw9nw7r4jl3agm3h9a;
ALTER TABLE IF EXISTS ONLY public.user_roles DROP CONSTRAINT IF EXISTS fkb4bms60ebskkrd05297us35x9;
ALTER TABLE IF EXISTS ONLY public.project_access DROP CONSTRAINT IF EXISTS fk7h7lvdypju02mo0g7ctp65lrm;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.user_roles DROP CONSTRAINT IF EXISTS user_roles_pkey;
ALTER TABLE IF EXISTS ONLY public.roles DROP CONSTRAINT IF EXISTS ukofx66keruapi6vyqpv6f2or37;
ALTER TABLE IF EXISTS ONLY public.project_access DROP CONSTRAINT IF EXISTS ukayx2ak354rf2jt4jxnt0brqq1;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS uk6dotkott2kjsp8vw4d0m25fb7;
ALTER TABLE IF EXISTS ONLY public.roles DROP CONSTRAINT IF EXISTS roles_pkey;
ALTER TABLE IF EXISTS ONLY public.projects DROP CONSTRAINT IF EXISTS projects_pkey;
ALTER TABLE IF EXISTS ONLY public.project_access DROP CONSTRAINT IF EXISTS project_access_pkey;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.user_roles;
DROP TABLE IF EXISTS public.roles;
DROP TABLE IF EXISTS public.projects;
DROP TABLE IF EXISTS public.project_access;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: project_access; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_access (
    id bigint NOT NULL,
    granted_at timestamp(6) without time zone NOT NULL,
    project_access_type character varying(255),
    project_uuid uuid NOT NULL,
    user_uuid uuid NOT NULL,
    CONSTRAINT project_access_project_access_type_check CHECK (((project_access_type)::text = ANY ((ARRAY['READ'::character varying, 'EDIT'::character varying])::text[])))
);


--
-- Name: project_access_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_access ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_access_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    uuid uuid NOT NULL,
    customer character varying(200) NOT NULL,
    department character varying(100) NOT NULL,
    description character varying(1000),
    end_date date NOT NULL,
    project_name character varying(200) NOT NULL,
    start_date date NOT NULL,
    status character varying(255) NOT NULL,
    department_head_uuid uuid NOT NULL,
    project_manager_uuid uuid CONSTRAINT projects_project_manager_id_not_null NOT NULL,
    CONSTRAINT projects_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(50) NOT NULL
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    user_uuid uuid NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    uuid uuid NOT NULL,
    department character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(50) NOT NULL,
    password character varying(100) NOT NULL,
    patronymic character varying(50) NOT NULL,
    registration_date timestamp(6) without time zone NOT NULL,
    surname character varying(50) NOT NULL
);


--
-- Data for Name: project_access; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.project_access (id, granted_at, project_access_type, project_uuid, user_uuid) FROM stdin;
1	2026-09-17 13:50:56.948243	EDIT	30a4fefb-8339-47d5-83ad-55706d37f23e	cb3e023b-7a0c-4f1a-8d1b-3c5917449e5c
2	2026-09-17 13:52:22.401569	READ	30a4fefb-8339-47d5-83ad-55706d37f23e	7c61dde3-2ea0-464d-a6d6-f44aeea678a1
3	2026-09-17 16:25:00.834639	READ	30a4fefb-8339-47d5-83ad-55706d37f23e	f9e3edc0-ae74-421b-94ba-598690ecf53c
\.


--
-- Data for Name: projects; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.projects (uuid, customer, department, description, end_date, project_name, start_date, status, department_head_uuid, project_manager_uuid) FROM stdin;
30a4fefb-8339-47d5-83ad-55706d37f23e	ООО "Технологии"	IT-отдел	Создание модуля аналитики для внутреннего использования	2027-03-31	Разработка нового модуля	2026-10-01	IN_PROGRESS	7c61dde3-2ea0-464d-a6d6-f44aeea678a1	cb3e023b-7a0c-4f1a-8d1b-3c5917449e5c
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles (id, description, name) FROM stdin;
1		Руководитель проекта
2		Начальник
3		Администратор
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.user_roles (user_uuid, role_id) FROM stdin;
f9e3edc0-ae74-421b-94ba-598690ecf53c	3
7c61dde3-2ea0-464d-a6d6-f44aeea678a1	3
7c61dde3-2ea0-464d-a6d6-f44aeea678a1	2
cb3e023b-7a0c-4f1a-8d1b-3c5917449e5c	1
cb3e023b-7a0c-4f1a-8d1b-3c5917449e5c	3
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (uuid, department, email, name, password, patronymic, registration_date, surname) FROM stdin;
f9e3edc0-ae74-421b-94ba-598690ecf53c	Отдел маркетинга	kate_1234@mail.ru	Екатерина	$2a$10$xMBW2oI2eykNUXJjwcxZ9eRBo50mRAl5tyCLWylcyLOVbjcj7ipCO	Сергеевна	2026-09-17 13:45:34.266309	Сорокина
cb3e023b-7a0c-4f1a-8d1b-3c5917449e5c	IT-отдел	oleg_kuznetsov@gmail.com	Олег	$2a$10$MVj//WhrZ9m13cdlXimdt.4qC2tFLAkidx5wae5GhK/KZODOeSE6u	Владимирович	2026-09-17 13:48:31.146151	Кузнецов
7c61dde3-2ea0-464d-a6d6-f44aeea678a1	IT-отдел	ann_novik@list.ru	Анна	$2a$10$kBcraq.KxD6cKtqYVeKnee0rlaLqiMQ8w6CXkBnCb5Ato/AQYcWw2	Максимовна	2026-09-17 13:47:14.584532	Новикова
\.


--
-- Name: project_access_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.project_access_id_seq', 3, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.roles_id_seq', 3, true);


--
-- Name: project_access project_access_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_access
    ADD CONSTRAINT project_access_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (uuid);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: project_access ukayx2ak354rf2jt4jxnt0brqq1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_access
    ADD CONSTRAINT ukayx2ak354rf2jt4jxnt0brqq1 UNIQUE (project_uuid, user_uuid);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_uuid, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (uuid);


--
-- Name: project_access fk7h7lvdypju02mo0g7ctp65lrm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_access
    ADD CONSTRAINT fk7h7lvdypju02mo0g7ctp65lrm FOREIGN KEY (user_uuid) REFERENCES public.users(uuid);


--
-- Name: user_roles fkb4bms60ebskkrd05297us35x9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkb4bms60ebskkrd05297us35x9 FOREIGN KEY (user_uuid) REFERENCES public.users(uuid);


--
-- Name: projects fkfk8sohdfw9nw7r4jl3agm3h9a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT fkfk8sohdfw9nw7r4jl3agm3h9a FOREIGN KEY (department_head_uuid) REFERENCES public.users(uuid);


--
-- Name: projects fkgdyu73mg454kk9iys9567qft7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT fkgdyu73mg454kk9iys9567qft7 FOREIGN KEY (project_manager_uuid) REFERENCES public.users(uuid);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: project_access fkmss0egoop5a53m3rsqerl68d0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_access
    ADD CONSTRAINT fkmss0egoop5a53m3rsqerl68d0 FOREIGN KEY (project_uuid) REFERENCES public.projects(uuid);


--
-- PostgreSQL database dump complete
--

\unrestrict fO0ykDwu2zhfypywCLgYo2y0NxQ8jTk2ozfHQE79X0e9oaFhRJQ0RZtuYQM5J5U

