--
-- PostgreSQL database dump
--

\restrict y4jZaMt8xWzm5E3d25ZyhzvmNUPeTa3c8p42zydJwCYK8ruCvva29uVb4Xcjp4q

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg13+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.project_access DROP CONSTRAINT IF EXISTS fkqt7aoej6h6qdy07le3g4hf9ka;
ALTER TABLE IF EXISTS ONLY public.user_roles DROP CONSTRAINT IF EXISTS fkhfh9dx7w3ubf1co1vdev94g3f;
ALTER TABLE IF EXISTS ONLY public.user_roles DROP CONSTRAINT IF EXISTS fkh8ciramu9cc9q3qcqiv4ue8a6;
ALTER TABLE IF EXISTS ONLY public.project_access DROP CONSTRAINT IF EXISTS fkgri7h552n5ta27ua0rwdhjnhn;
ALTER TABLE IF EXISTS ONLY public.projects DROP CONSTRAINT IF EXISTS fkgdyu73mg454kk9iys9567qft7;
ALTER TABLE IF EXISTS ONLY public.projects DROP CONSTRAINT IF EXISTS fkepqh730ekki8irhfb4hmmni09;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.user_roles DROP CONSTRAINT IF EXISTS user_roles_pkey;
ALTER TABLE IF EXISTS ONLY public.roles DROP CONSTRAINT IF EXISTS ukofx66keruapi6vyqpv6f2or37;
ALTER TABLE IF EXISTS ONLY public.project_access DROP CONSTRAINT IF EXISTS ukk6pe8xsn01koxgcvupp0j2yik;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS uk6dotkott2kjsp8vw4d0m25fb7;
ALTER TABLE IF EXISTS ONLY public.roles DROP CONSTRAINT IF EXISTS roles_pkey;
ALTER TABLE IF EXISTS ONLY public.projects DROP CONSTRAINT IF EXISTS projects_pkey;
ALTER TABLE IF EXISTS ONLY public.project_access DROP CONSTRAINT IF EXISTS project_access_pkey;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.user_roles;
DROP TABLE IF EXISTS public.roles;
DROP TABLE IF EXISTS public.projects;
DROP TABLE IF EXISTS public.project_access;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: project_access; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_access (
    id bigint NOT NULL,
    granted_at timestamp(6) without time zone NOT NULL,
    project_access_type character varying(255),
    project_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT project_access_project_access_type_check CHECK (((project_access_type)::text = ANY ((ARRAY['READ'::character varying, 'EDIT'::character varying])::text[])))
);


--
-- Name: project_access_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_access ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_access_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id bigint NOT NULL,
    customer character varying(200) NOT NULL,
    department character varying(100) NOT NULL,
    description character varying(1000),
    end_date date NOT NULL,
    project_name character varying(200) NOT NULL,
    start_date date NOT NULL,
    status character varying(255) NOT NULL,
    department_head_id bigint NOT NULL,
    project_manager_id bigint NOT NULL,
    CONSTRAINT projects_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(50) NOT NULL
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    department character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(50) NOT NULL,
    password character varying(100) NOT NULL,
    patronymic character varying(50) NOT NULL,
    registration_date timestamp(6) without time zone NOT NULL,
    surname character varying(50) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: project_access; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.project_access (id, granted_at, project_access_type, project_id, user_id) FROM stdin;
2	2026-09-17 00:15:02.162411	EDIT	3	1
3	2026-09-17 00:16:20.619938	EDIT	3	2
35	2026-09-17 11:01:05.945475	READ	3	3
\.


--
-- Data for Name: projects; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.projects (id, customer, department, description, end_date, project_name, start_date, status, department_head_id, project_manager_id) FROM stdin;
3	ООО "Технологии"	IT-отдел	Создание модуля аналитики для внутреннего использования	2027-03-31	Разработка нового модуля	2026-10-01	IN_PROGRESS	2	1
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles (id, description, name) FROM stdin;
1		Руководитель проекта
2		Начальник
3		Администратор
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.user_roles (user_id, role_id) FROM stdin;
1	1
1	3
2	3
2	2
3	3
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, department, email, name, password, patronymic, registration_date, surname) FROM stdin;
1	Отдел разработки	oleg_kuznetsov@gmail.com	Олег	$2a$10$SNBEo77vbuJTayyNbUiOPeeJVbSN2etIzbIejcejU7lS2x1DrXEKi	Владимирович	2026-09-14 20:10:00.366082	Кузнецов
2	Отдел маркетинга	ann_novik@mail.com	Анна	$2a$10$J.B5O6/HR8HDTpCKsuH46elTwrJHeXTACHoOZbgPgb1WGTkZ5rOdC	Максимовна	2026-09-14 22:54:49.427996	Новикова
3	Отдел маркетинга	kate_1234@mail.ru	Екатерина	$2a$10$lZvPPWtRu8U01Ulxj7V4JO3BlbAmkEWmMV8orOY2oRS8.QXNPNVa.	Сергеевна	2026-09-17 11:00:07.448275	Сорокина
\.


--
-- Name: project_access_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.project_access_id_seq', 35, true);


--
-- Name: projects_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.projects_id_seq', 35, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.roles_id_seq', 3, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- Name: project_access project_access_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_access
    ADD CONSTRAINT project_access_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: project_access ukk6pe8xsn01koxgcvupp0j2yik; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_access
    ADD CONSTRAINT ukk6pe8xsn01koxgcvupp0j2yik UNIQUE (project_id, user_id);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: projects fkepqh730ekki8irhfb4hmmni09; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT fkepqh730ekki8irhfb4hmmni09 FOREIGN KEY (department_head_id) REFERENCES public.users(id);


--
-- Name: projects fkgdyu73mg454kk9iys9567qft7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT fkgdyu73mg454kk9iys9567qft7 FOREIGN KEY (project_manager_id) REFERENCES public.users(id);


--
-- Name: project_access fkgri7h552n5ta27ua0rwdhjnhn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_access
    ADD CONSTRAINT fkgri7h552n5ta27ua0rwdhjnhn FOREIGN KEY (project_id) REFERENCES public.projects(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: project_access fkqt7aoej6h6qdy07le3g4hf9ka; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_access
    ADD CONSTRAINT fkqt7aoej6h6qdy07le3g4hf9ka FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict y4jZaMt8xWzm5E3d25ZyhzvmNUPeTa3c8p42zydJwCYK8ruCvva29uVb4Xcjp4q

